Repository DUNE-DAQ/appfwk, pull requests merged in 2020-06, with the labels that each got.

#20 Remove Issue header files
  include/app-framework/DAQProcess.hh
  include/app-framework/DAQProcessIssues.hh
  src/DAQModules/FakeDataConsumerDAQModule.cc
  src/DAQModules/FakeDataProducerDAQModule.cc
  src/DAQProcess.cc
Labels: enhancement

#41 restore copy push for DAQSink
  include/appfwk/DAQSink.hpp
  include/appfwk/FanOutDAQModule.hpp
Labels: bug, code style, enhancement

#47 fix seg fault and add empty constructor
  include/appfwk/FanOutDAQModule.hpp
  include/appfwk/detail/FanOutDAQModule.hxx
Labels: bug

#44 Adding command registration
  CMakeLists.txt
  include/appfwk/DAQModule.hpp
  include/appfwk/FanOutDAQModule.hpp
  include/appfwk/StdDeQueue.hpp
  include/appfwk/detail/DAQModule.hxx
  include/appfwk/detail/FanOutDAQModule.hxx
  include/appfwk/detail/StdDeQueue.hxx
  src/DAQModule.cpp
  src/DAQProcess.cpp
  test/DebugLoggingDAQModule.hpp
  test/DummyModule.cpp
  test/DummyModule.hpp
  test/FakeDataConsumerDAQModule.cpp
  test/FakeDataConsumerDAQModule.hpp
  test/FakeDataProducerDAQModule.cpp
  test/FakeDataProducerDAQModule.hpp
  test/dummy_test_app.cxx
Labels: enhancement
